const documentsA = [
    {
        id: "A001",
        label: "Ganapathi_suktham_rigvedam",
        description: "Ganapathi_suktham_rigvedam",
        keywords: "Ganapathi_suktham_rigvedam",
        file: CATEGORY_A_FOLDER + "Ganapathi_suktham_rigvedam.pdf",
    },
    {
        id: "A006",
        label: "Pavamaana_suktham",
        description: "Pavamaana_suktham",
        keywords: "Pavamaana_suktham",
        file: CATEGORY_A_FOLDER + "Pavamaana_suktham.pdf",
    },
    {
        id: "A018",
        label: "Kumaara_suktham",
        description: "Kumaara_suktham",
        keywords: "Kumaara_suktham",
        file: CATEGORY_A_FOLDER + "Kumaara_suktham.pdf",
    },
    {
        id: "A015",
        label: "Shri_rudram_chamakam",
        description: "Shri_rudram_chamakam",
        keywords: "Shri_rudram_chamakam",
        file: CATEGORY_A_FOLDER + "Shri_rudram_chamakam.pdf",
    },
    {
        id: "A013",
        label: "Rudra_chamaka_krama_paatam",
        description: "Rudra_chamaka_krama_paatam",
        keywords: "Rudra_chamaka_krama_paatam",
        file: CATEGORY_A_FOLDER + "Rudra_chamaka_krama_paatam.pdf",
    },
    {
        id: "A007",
        label: "Purusha_suktham",
        description: "Purusha_suktham",
        keywords: "Purusha_suktham",
        file: CATEGORY_A_FOLDER + "Purusha_suktham.pdf",
    },
    {
        id: "A008",
        label: "Shri_suktham_rigvedam",
        description: "Shri_suktham_rigvedam",
        keywords: "Shri_suktham_rigvedam",
        file: CATEGORY_A_FOLDER + "Shri_suktham_rigvedam.pdf",
    },
    {
        id: "A005",
        label: "Durga_suktham",
        description: "Durga_suktham",
        keywords: "Durga_suktham",
        file: CATEGORY_A_FOLDER + "Durga_suktham.pdf",
    },
    {
        id: "A004",
        label: "Narayana_suktham",
        description: "Narayana_suktham",
        keywords: "Narayana_suktham",
        file: CATEGORY_A_FOLDER + "Narayana_suktham.pdf",
    },
    {
        id: "A003",
        label: "Nakshatra_suktham",
        description: "Nakshatra_suktham",
        keywords: "Nakshatra_suktham",
        file: CATEGORY_A_FOLDER + "Nakshatra_suktham.pdf",
    },
    {
        id: "A002",
        label: "Arunaprashnam",
        description: "Arunaprashnam",
        keywords: "Arunaprashnam",
        file: CATEGORY_A_FOLDER + "Arunaprashnam.pdf",
    },
    {
        id: "A009",
        label: "Medha_suktham",
        description: "Medha_suktham",
        keywords: "Medha_suktham",
        file: CATEGORY_A_FOLDER + "Medha_suktham.pdf",
    },
    {
        id: "A010",
        label: "Neela_suktham",
        description: "Neela_suktham",
        keywords: "Neela_suktham",
        file: CATEGORY_A_FOLDER + "Neela_suktham.pdf",
    },
    {
        id: "A011",
        label: "Vishnu_suktham",
        description: "Vishnu_suktham",
        keywords: "Vishnu_suktham",
        file: CATEGORY_A_FOLDER + "Vishnu_suktham.pdf",
    },
    {
        id: "A012",
        label: "Bhaagya_suktham",
        description: "Bhaagya_suktham",
        keywords: "Bhaagya_suktham",
        file: CATEGORY_A_FOLDER + "Bhaagya_suktham.pdf",
    },
    {
        id: "A014",
        label: "Surya_namaskaaram_poorvaangam",
        description: "Surya_namaskaaram_poorvaangam",
        keywords: "Surya_namaskaaram_poorvaangam",
        file: CATEGORY_A_FOLDER + "Surya_namaskaaram_poorvaangam.pdf",
    },
    {
        id: "A016",
        label: "Udaka_shanthi",
        description: "Udaka_shanthi",
        keywords: "Udaka_shanthi",
        file: CATEGORY_A_FOLDER + "Udaka_shanthi.pdf",
    },
    {
        id: "A017",
        label: "Shiva_sthuthi",
        description: "Shiva_sthuthi",
        keywords: "Shiva_sthuthi",
        file: CATEGORY_A_FOLDER + "Shiva_sthuthi.pdf",
    },
    {
        id: "A019",
        label: "Bhu_suktham",
        description: "Bhu_suktham",
        keywords: "Bhu_suktham",
        file: CATEGORY_A_FOLDER + "Bhu_suktham.pdf",
    },
    {
        id: "A020",
        label: "Shri_hanumath_suktham",
        description: "Shri_hanumath_suktham",
        keywords: "Shri_hanumath_suktham",
        file: CATEGORY_A_FOLDER + "Shri_hanumath_suktham.pdf",
    },
];