//
// Category names
//

const categories =
{
    A: "Vedam",
    B: "Ashtottharam",
    C: "Shlokam",
    D: "Paarayanam",
    E: "TBD - Cat E",
    F: "TBD - Cat F",
    G: "Shri Rama",
    H: "TBD - Cat H",
    I: "TBD - Cat I",
    J: "TBD - Cat J",
    K: "TBD - Cat K",
    L: "TBD - Cat L",
    M: "TBD - Cat M",
    N: "TBD - Cat N",
    O: "TBD - Cat O",
    P: "TBD - Cat P",
    Q: "TBD - Cat Q",
    R: "TBD - Cat R",
    S: "TBD - Cat S",
    T: "TBD - Cat T",
};

//
// Category folders
//

const categoryFolders =
{
    A: "pdf/categoryA/",
    B: "pdf/categoryB/",
    C: "pdf/categoryC/",
    D: "pdf/categoryD/",
    E: "pdf/categoryE/",
    F: "pdf/categoryF/",
    G: "pdf/categoryG/",
    H: "pdf/categoryH/",
    I: "pdf/categoryI/",
    J: "pdf/categoryJ/",
    K: "pdf/categoryK/",
    L: "pdf/categoryL/",
    M: "pdf/categoryM/",
    N: "pdf/categoryN/",
    O: "pdf/categoryO/",
    P: "pdf/categoryP/",
    Q: "pdf/categoryQ/",
    R: "pdf/categoryR/",
    S: "pdf/categoryS/",
    T: "pdf/categoryT/",
};

//
// Documents
//

const documents =
{
    A:
    [
        {
            id: "A001",
            label: "Ganapathi_suktham_rigvedam",
            description: "Ganapathi_suktham_rigvedam",
            keywords: "Ganapathi_suktham_rigvedam",
            file: categoryFolders.A + "Ganapathi_suktham_rigvedam.pdf",
        },
        {
            id: "A006",
            label: "Pavamaana_suktham",
            description: "Pavamaana_suktham",
            keywords: "Pavamaana_suktham",
            file: categoryFolders.A + "Pavamaana_suktham.pdf",
        },
        {
            id: "A018",
            label: "Kumaara_suktham",
            description: "Kumaara_suktham",
            keywords: "Kumaara_suktham",
            file: categoryFolders.A + "Kumaara_suktham.pdf",
        },
        {
            id: "A015",
            label: "Shri_rudram_chamakam",
            description: "Shri_rudram_chamakam",
            keywords: "Shri_rudram_chamakam",
            file: categoryFolders.A + "Shri_rudram_chamakam.pdf",
        },
        {
            id: "A013",
            label: "Rudra_chamaka_krama_paatam",
            description: "Rudra_chamaka_krama_paatam",
            keywords: "Rudra_chamaka_krama_paatam",
            file: categoryFolders.A + "Rudra_chamaka_krama_paatam.pdf",
        },
        {
            id: "A007",
            label: "Purusha_suktham",
            description: "Purusha_suktham",
            keywords: "Purusha_suktham",
            file: categoryFolders.A + "Purusha_suktham.pdf",
        },
        {
            id: "A008",
            label: "Shri_suktham_rigvedam",
            description: "Shri_suktham_rigvedam",
            keywords: "Shri_suktham_rigvedam",
            file: categoryFolders.A + "Shri_suktham_rigvedam.pdf",
        },
        {
            id: "A005",
            label: "Durga_suktham",
            description: "Durga_suktham",
            keywords: "Durga_suktham",
            file: categoryFolders.A + "Durga_suktham.pdf",
        },
        {
            id: "A004",
            label: "Narayana_suktham",
            description: "Narayana_suktham",
            keywords: "Narayana_suktham",
            file: categoryFolders.A + "Narayana_suktham.pdf",
        },
        {
            id: "A003",
            label: "Nakshatra_suktham",
            description: "Nakshatra_suktham",
            keywords: "Nakshatra_suktham",
            file: categoryFolders.A + "Nakshatra_suktham.pdf",
        },
        {
            id: "A002",
            label: "Arunaprashnam",
            description: "Arunaprashnam",
            keywords: "Arunaprashnam",
            file: categoryFolders.A + "Arunaprashnam.pdf",
        },
        {
            id: "A009",
            label: "Medha_suktham",
            description: "Medha_suktham",
            keywords: "Medha_suktham",
            file: categoryFolders.A + "Medha_suktham.pdf",
        },
        {
            id: "A010",
            label: "Neela_suktham",
            description: "Neela_suktham",
            keywords: "Neela_suktham",
            file: categoryFolders.A + "Neela_suktham.pdf",
        },
        {
            id: "A011",
            label: "Vishnu_suktham",
            description: "Vishnu_suktham",
            keywords: "Vishnu_suktham",
            file: categoryFolders.A + "Vishnu_suktham.pdf",
        },
        {
            id: "A012",
            label: "Bhaagya_suktham",
            description: "Bhaagya_suktham",
            keywords: "Bhaagya_suktham",
            file: categoryFolders.A + "Bhaagya_suktham.pdf",
        },
        {
            id: "A014",
            label: "Surya_namaskaaram_poorvaangam",
            description: "Surya_namaskaaram_poorvaangam",
            keywords: "Surya_namaskaaram_poorvaangam",
            file: categoryFolders.A + "Surya_namaskaaram_poorvaangam.pdf",
        },
        {
            id: "A016",
            label: "Udaka_shanthi",
            description: "Udaka_shanthi",
            keywords: "Udaka_shanthi",
            file: categoryFolders.A + "Udaka_shanthi.pdf",
        },
        {
            id: "A017",
            label: "Shiva_sthuthi",
            description: "Shiva_sthuthi",
            keywords: "Shiva_sthuthi",
            file: categoryFolders.A + "Shiva_sthuthi.pdf",
        },
        {
            id: "A019",
            label: "Bhu_suktham",
            description: "Bhu_suktham",
            keywords: "Bhu_suktham",
            file: categoryFolders.A + "Bhu_suktham.pdf",
        },
        {
            id: "A023",
            label: "Nakshatra_suktham",
            description: "Nakshatra_suktham",
            keywords: "Nakshatra_suktham",
            file: categoryFolders.A + "Nakshatra_suktham.pdf",
        },
        {
            id: "A020",
            label: "Shri_hanumath_suktham",
            description: "Shri_hanumath_suktham",
            keywords: "Shri_hanumath_suktham",
            file: categoryFolders.A + "Shri_hanumath_suktham.pdf",
        },
        {
            id: "A038",
            label: "Kumaara_suktham",
            description: "Kumaara_suktham",
            keywords: "Kumaara_suktham",
            file: categoryFolders.A + "Kumaara_suktham.pdf",
        },
        {
            id: "A026",
            label: "Pavamaana_suktham",
            description: "Pavamaana_suktham",
            keywords: "Pavamaana_suktham",
            file: categoryFolders.A + "Pavamaana_suktham.pdf",
        },
        {
            id: "A021",
            label: "Ganapathi_suktham_rigvedam",
            description: "Ganapathi_suktham_rigvedam",
            keywords: "Ganapathi_suktham_rigvedam",
            file: categoryFolders.A + "Ganapathi_suktham_rigvedam.pdf",
        },
        {
            id: "A035",
            label: "Shri_rudram_chamakam",
            description: "Shri_rudram_chamakam",
            keywords: "Shri_rudram_chamakam",
            file: categoryFolders.A + "Shri_rudram_chamakam.pdf",
        },
        {
            id: "A033",
            label: "Rudra_chamaka_krama_paatam",
            description: "Rudra_chamaka_krama_paatam",
            keywords: "Rudra_chamaka_krama_paatam",
            file: categoryFolders.A + "Rudra_chamaka_krama_paatam.pdf",
        },
        {
            id: "A027",
            label: "Purusha_suktham",
            description: "Purusha_suktham",
            keywords: "Purusha_suktham",
            file: categoryFolders.A + "Purusha_suktham.pdf",
        },
        {
            id: "A028",
            label: "Shri_suktham_rigvedam",
            description: "Shri_suktham_rigvedam",
            keywords: "Shri_suktham_rigvedam",
            file: categoryFolders.A + "Shri_suktham_rigvedam.pdf",
        },
        {
            id: "A025",
            label: "Durga_suktham",
            description: "Durga_suktham",
            keywords: "Durga_suktham",
            file: categoryFolders.A + "Durga_suktham.pdf",
        },
        {
            id: "A024",
            label: "Narayana_suktham",
            description: "Narayana_suktham",
            keywords: "Narayana_suktham",
            file: categoryFolders.A + "Narayana_suktham.pdf",
        },
        {
            id: "A022",
            label: "Arunaprashnam",
            description: "Arunaprashnam",
            keywords: "Arunaprashnam",
            file: categoryFolders.A + "Arunaprashnam.pdf",
        },
        {
            id: "A029",
            label: "Medha_suktham",
            description: "Medha_suktham",
            keywords: "Medha_suktham",
            file: categoryFolders.A + "Medha_suktham.pdf",
        },
        {
            id: "A030",
            label: "Neela_suktham",
            description: "Neela_suktham",
            keywords: "Neela_suktham",
            file: categoryFolders.A + "Neela_suktham.pdf",
        },
        {
            id: "A031",
            label: "Vishnu_suktham",
            description: "Vishnu_suktham",
            keywords: "Vishnu_suktham",
            file: categoryFolders.A + "Vishnu_suktham.pdf",
        },
        {
            id: "A032",
            label: "Bhaagya_suktham",
            description: "Bhaagya_suktham",
            keywords: "Bhaagya_suktham",
            file: categoryFolders.A + "Bhaagya_suktham.pdf",
        },
        {
            id: "A034",
            label: "Surya_namaskaaram_poorvaangam",
            description: "Surya_namaskaaram_poorvaangam",
            keywords: "Surya_namaskaaram_poorvaangam",
            file: categoryFolders.A + "Surya_namaskaaram_poorvaangam.pdf",
        },
        {
            id: "A036",
            label: "Udaka_shanthi",
            description: "Udaka_shanthi",
            keywords: "Udaka_shanthi",
            file: categoryFolders.A + "Udaka_shanthi.pdf",
        },
        {
            id: "A037",
            label: "Shiva_sthuthi",
            description: "Shiva_sthuthi",
            keywords: "Shiva_sthuthi",
            file: categoryFolders.A + "Shiva_sthuthi.pdf",
        },
        {
            id: "A039",
            label: "Bhu_suktham",
            description: "Bhu_suktham",
            keywords: "Bhu_suktham",
            file: categoryFolders.A + "Bhu_suktham.pdf",
        },
        {
            id: "A040",
            label: "Shri_hanumath_suktham",
            description: "Shri_hanumath_suktham",
            keywords: "Shri_hanumath_suktham",
            file: categoryFolders.A + "Shri_hanumath_suktham.pdf",
        },
    ],
    B:
    [
        {
            id: "B001",
            label: "Ganapathi_suktham_rigvedam",
            description: "Ganapathi_suktham_rigvedam",
            keywords: "Ganapathi_suktham_rigvedam",
            file: categoryFolders.B + "Ganapathi_suktham_rigvedam.pdf",
        },
        {
            id: "B006",
            label: "Pavamaana_suktham",
            description: "Pavamaana_suktham",
            keywords: "Pavamaana_suktham",
            file: categoryFolders.B + "Pavamaana_suktham.pdf",
        },
        {
            id: "B018",
            label: "Kumaara_suktham",
            description: "Kumaara_suktham",
            keywords: "Kumaara_suktham",
            file: categoryFolders.B + "Kumaara_suktham.pdf",
        },
        {
            id: "B015",
            label: "Shri_rudram_chamakam",
            description: "Shri_rudram_chamakam",
            keywords: "Shri_rudram_chamakam",
            file: categoryFolders.B + "Shri_rudram_chamakam.pdf",
        },
        {
            id: "B013",
            label: "Rudra_chamaka_krama_paatam",
            description: "Rudra_chamaka_krama_paatam",
            keywords: "Rudra_chamaka_krama_paatam",
            file: categoryFolders.B + "Rudra_chamaka_krama_paatam.pdf",
        },
        {
            id: "B007",
            label: "Purusha_suktham",
            description: "Purusha_suktham",
            keywords: "Purusha_suktham",
            file: categoryFolders.B + "Purusha_suktham.pdf",
        },
        {
            id: "B008",
            label: "Shri_suktham_rigvedam",
            description: "Shri_suktham_rigvedam",
            keywords: "Shri_suktham_rigvedam",
            file: categoryFolders.B + "Shri_suktham_rigvedam.pdf",
        },
        {
            id: "B005",
            label: "Durga_suktham",
            description: "Durga_suktham",
            keywords: "Durga_suktham",
            file: categoryFolders.B + "Durga_suktham.pdf",
        },
        {
            id: "B004",
            label: "Narayana_suktham",
            description: "Narayana_suktham",
            keywords: "Narayana_suktham",
            file: categoryFolders.B + "Narayana_suktham.pdf",
        },
        {
            id: "B003",
            label: "Nakshatra_suktham",
            description: "Nakshatra_suktham",
            keywords: "Nakshatra_suktham",
            file: categoryFolders.B + "Nakshatra_suktham.pdf",
        },
        {
            id: "B002",
            label: "Arunaprashnam",
            description: "Arunaprashnam",
            keywords: "Arunaprashnam",
            file: categoryFolders.B + "Arunaprashnam.pdf",
        },
        {
            id: "B009",
            label: "Medha_suktham",
            description: "Medha_suktham",
            keywords: "Medha_suktham",
            file: categoryFolders.B + "Medha_suktham.pdf",
        },
        {
            id: "B010",
            label: "Neela_suktham",
            description: "Neela_suktham",
            keywords: "Neela_suktham",
            file: categoryFolders.B + "Neela_suktham.pdf",
        },
        {
            id: "B011",
            label: "Vishnu_suktham",
            description: "Vishnu_suktham",
            keywords: "Vishnu_suktham",
            file: categoryFolders.B + "Vishnu_suktham.pdf",
        },
        {
            id: "B012",
            label: "Bhaagya_suktham",
            description: "Bhaagya_suktham",
            keywords: "Bhaagya_suktham",
            file: categoryFolders.B + "Bhaagya_suktham.pdf",
        },
        {
            id: "B014",
            label: "Surya_namaskaaram_poorvaangam",
            description: "Surya_namaskaaram_poorvaangam",
            keywords: "Surya_namaskaaram_poorvaangam",
            file: categoryFolders.B + "Surya_namaskaaram_poorvaangam.pdf",
        },
        {
            id: "B016",
            label: "Udaka_shanthi",
            description: "Udaka_shanthi",
            keywords: "Udaka_shanthi",
            file: categoryFolders.B + "Udaka_shanthi.pdf",
        },
        {
            id: "B017",
            label: "Shiva_sthuthi",
            description: "Shiva_sthuthi",
            keywords: "Shiva_sthuthi",
            file: categoryFolders.B + "Shiva_sthuthi.pdf",
        },
        {
            id: "B019",
            label: "Bhu_suktham",
            description: "Bhu_suktham",
            keywords: "Bhu_suktham",
            file: categoryFolders.B + "Bhu_suktham.pdf",
        },
        {
            id: "B023",
            label: "Nakshatra_suktham",
            description: "Nakshatra_suktham",
            keywords: "Nakshatra_suktham",
            file: categoryFolders.B + "Nakshatra_suktham.pdf",
        },
        {
            id: "B020",
            label: "Shri_hanumath_suktham",
            description: "Shri_hanumath_suktham",
            keywords: "Shri_hanumath_suktham",
            file: categoryFolders.B + "Shri_hanumath_suktham.pdf",
        },
        {
            id: "B038",
            label: "Kumaara_suktham",
            description: "Kumaara_suktham",
            keywords: "Kumaara_suktham",
            file: categoryFolders.B + "Kumaara_suktham.pdf",
        },
        {
            id: "B026",
            label: "Pavamaana_suktham",
            description: "Pavamaana_suktham",
            keywords: "Pavamaana_suktham",
            file: categoryFolders.B + "Pavamaana_suktham.pdf",
        },
        {
            id: "B021",
            label: "Ganapathi_suktham_rigvedam",
            description: "Ganapathi_suktham_rigvedam",
            keywords: "Ganapathi_suktham_rigvedam",
            file: categoryFolders.B + "Ganapathi_suktham_rigvedam.pdf",
        },
        {
            id: "B035",
            label: "Shri_rudram_chamakam",
            description: "Shri_rudram_chamakam",
            keywords: "Shri_rudram_chamakam",
            file: categoryFolders.B + "Shri_rudram_chamakam.pdf",
        },
        {
            id: "B033",
            label: "Rudra_chamaka_krama_paatam",
            description: "Rudra_chamaka_krama_paatam",
            keywords: "Rudra_chamaka_krama_paatam",
            file: categoryFolders.B + "Rudra_chamaka_krama_paatam.pdf",
        },
        {
            id: "B027",
            label: "Purusha_suktham",
            description: "Purusha_suktham",
            keywords: "Purusha_suktham",
            file: categoryFolders.B + "Purusha_suktham.pdf",
        },
        {
            id: "B028",
            label: "Shri_suktham_rigvedam",
            description: "Shri_suktham_rigvedam",
            keywords: "Shri_suktham_rigvedam",
            file: categoryFolders.B + "Shri_suktham_rigvedam.pdf",
        },
        {
            id: "B025",
            label: "Durga_suktham",
            description: "Durga_suktham",
            keywords: "Durga_suktham",
            file: categoryFolders.B + "Durga_suktham.pdf",
        },
        {
            id: "B024",
            label: "Narayana_suktham",
            description: "Narayana_suktham",
            keywords: "Narayana_suktham",
            file: categoryFolders.B + "Narayana_suktham.pdf",
        },
        {
            id: "B022",
            label: "Arunaprashnam",
            description: "Arunaprashnam",
            keywords: "Arunaprashnam",
            file: categoryFolders.B + "Arunaprashnam.pdf",
        },
        {
            id: "B029",
            label: "Medha_suktham",
            description: "Medha_suktham",
            keywords: "Medha_suktham",
            file: categoryFolders.B + "Medha_suktham.pdf",
        },
        {
            id: "B030",
            label: "Neela_suktham",
            description: "Neela_suktham",
            keywords: "Neela_suktham",
            file: categoryFolders.B + "Neela_suktham.pdf",
        },
        {
            id: "B031",
            label: "Vishnu_suktham",
            description: "Vishnu_suktham",
            keywords: "Vishnu_suktham",
            file: categoryFolders.B + "Vishnu_suktham.pdf",
        },
        {
            id: "B032",
            label: "Bhaagya_suktham",
            description: "Bhaagya_suktham",
            keywords: "Bhaagya_suktham",
            file: categoryFolders.B + "Bhaagya_suktham.pdf",
        },
        {
            id: "B034",
            label: "Surya_namaskaaram_poorvaangam",
            description: "Surya_namaskaaram_poorvaangam",
            keywords: "Surya_namaskaaram_poorvaangam",
            file: categoryFolders.B + "Surya_namaskaaram_poorvaangam.pdf",
        },
        {
            id: "B036",
            label: "Udaka_shanthi",
            description: "Udaka_shanthi",
            keywords: "Udaka_shanthi",
            file: categoryFolders.B + "Udaka_shanthi.pdf",
        },
        {
            id: "B037",
            label: "Shiva_sthuthi",
            description: "Shiva_sthuthi",
            keywords: "Shiva_sthuthi",
            file: categoryFolders.B + "Shiva_sthuthi.pdf",
        },
        {
            id: "B039",
            label: "Bhu_suktham",
            description: "Bhu_suktham",
            keywords: "Bhu_suktham",
            file: categoryFolders.B + "Bhu_suktham.pdf",
        },
        {
            id: "B040",
            label: "Shri_hanumath_suktham",
            description: "Shri_hanumath_suktham",
            keywords: "Shri_hanumath_suktham",
            file: categoryFolders.B + "Shri_hanumath_suktham.pdf",
        },
    ],
    C:
    [
        {
            id: "C001",
            label: "Ganapathi_suktham_rigvedam",
            description: "Ganapathi_suktham_rigvedam",
            keywords: "Ganapathi_suktham_rigvedam",
            file: categoryFolders.C + "Ganapathi_suktham_rigvedam.pdf",
        },
        {
            id: "C006",
            label: "Pavamaana_suktham",
            description: "Pavamaana_suktham",
            keywords: "Pavamaana_suktham",
            file: categoryFolders.C + "Pavamaana_suktham.pdf",
        },
        {
            id: "C018",
            label: "Kumaara_suktham",
            description: "Kumaara_suktham",
            keywords: "Kumaara_suktham",
            file: categoryFolders.C + "Kumaara_suktham.pdf",
        },
        {
            id: "C015",
            label: "Shri_rudram_chamakam",
            description: "Shri_rudram_chamakam",
            keywords: "Shri_rudram_chamakam",
            file: categoryFolders.C + "Shri_rudram_chamakam.pdf",
        },
        {
            id: "C013",
            label: "Rudra_chamaka_krama_paatam",
            description: "Rudra_chamaka_krama_paatam",
            keywords: "Rudra_chamaka_krama_paatam",
            file: categoryFolders.C + "Rudra_chamaka_krama_paatam.pdf",
        },
        {
            id: "C007",
            label: "Purusha_suktham",
            description: "Purusha_suktham",
            keywords: "Purusha_suktham",
            file: categoryFolders.C + "Purusha_suktham.pdf",
        },
        {
            id: "C008",
            label: "Shri_suktham_rigvedam",
            description: "Shri_suktham_rigvedam",
            keywords: "Shri_suktham_rigvedam",
            file: categoryFolders.C + "Shri_suktham_rigvedam.pdf",
        },
        {
            id: "C005",
            label: "Durga_suktham",
            description: "Durga_suktham",
            keywords: "Durga_suktham",
            file: categoryFolders.C + "Durga_suktham.pdf",
        },
        {
            id: "C004",
            label: "Narayana_suktham",
            description: "Narayana_suktham",
            keywords: "Narayana_suktham",
            file: categoryFolders.C + "Narayana_suktham.pdf",
        },
        {
            id: "C003",
            label: "Nakshatra_suktham",
            description: "Nakshatra_suktham",
            keywords: "Nakshatra_suktham",
            file: categoryFolders.C + "Nakshatra_suktham.pdf",
        },
        {
            id: "C002",
            label: "Arunaprashnam",
            description: "Arunaprashnam",
            keywords: "Arunaprashnam",
            file: categoryFolders.C + "Arunaprashnam.pdf",
        },
        {
            id: "C009",
            label: "Medha_suktham",
            description: "Medha_suktham",
            keywords: "Medha_suktham",
            file: categoryFolders.C + "Medha_suktham.pdf",
        },
        {
            id: "C010",
            label: "Neela_suktham",
            description: "Neela_suktham",
            keywords: "Neela_suktham",
            file: categoryFolders.C + "Neela_suktham.pdf",
        },
        {
            id: "C011",
            label: "Vishnu_suktham",
            description: "Vishnu_suktham",
            keywords: "Vishnu_suktham",
            file: categoryFolders.C + "Vishnu_suktham.pdf",
        },
        {
            id: "C012",
            label: "Bhaagya_suktham",
            description: "Bhaagya_suktham",
            keywords: "Bhaagya_suktham",
            file: categoryFolders.C + "Bhaagya_suktham.pdf",
        },
        {
            id: "C014",
            label: "Surya_namaskaaram_poorvaangam",
            description: "Surya_namaskaaram_poorvaangam",
            keywords: "Surya_namaskaaram_poorvaangam",
            file: categoryFolders.C + "Surya_namaskaaram_poorvaangam.pdf",
        },
        {
            id: "C016",
            label: "Udaka_shanthi",
            description: "Udaka_shanthi",
            keywords: "Udaka_shanthi",
            file: categoryFolders.C + "Udaka_shanthi.pdf",
        },
        {
            id: "C017",
            label: "Shiva_sthuthi",
            description: "Shiva_sthuthi",
            keywords: "Shiva_sthuthi",
            file: categoryFolders.C + "Shiva_sthuthi.pdf",
        },
        {
            id: "C019",
            label: "Bhu_suktham",
            description: "Bhu_suktham",
            keywords: "Bhu_suktham",
            file: categoryFolders.C + "Bhu_suktham.pdf",
        },
        {
            id: "C023",
            label: "Nakshatra_suktham",
            description: "Nakshatra_suktham",
            keywords: "Nakshatra_suktham",
            file: categoryFolders.C + "Nakshatra_suktham.pdf",
        },
        {
            id: "C020",
            label: "Shri_hanumath_suktham",
            description: "Shri_hanumath_suktham",
            keywords: "Shri_hanumath_suktham",
            file: categoryFolders.C + "Shri_hanumath_suktham.pdf",
        },
        {
            id: "C038",
            label: "Kumaara_suktham",
            description: "Kumaara_suktham",
            keywords: "Kumaara_suktham",
            file: categoryFolders.C + "Kumaara_suktham.pdf",
        },
        {
            id: "C026",
            label: "Pavamaana_suktham",
            description: "Pavamaana_suktham",
            keywords: "Pavamaana_suktham",
            file: categoryFolders.C + "Pavamaana_suktham.pdf",
        },
        {
            id: "C021",
            label: "Ganapathi_suktham_rigvedam",
            description: "Ganapathi_suktham_rigvedam",
            keywords: "Ganapathi_suktham_rigvedam",
            file: categoryFolders.C + "Ganapathi_suktham_rigvedam.pdf",
        },
        {
            id: "C035",
            label: "Shri_rudram_chamakam",
            description: "Shri_rudram_chamakam",
            keywords: "Shri_rudram_chamakam",
            file: categoryFolders.C + "Shri_rudram_chamakam.pdf",
        },
        {
            id: "C033",
            label: "Rudra_chamaka_krama_paatam",
            description: "Rudra_chamaka_krama_paatam",
            keywords: "Rudra_chamaka_krama_paatam",
            file: categoryFolders.C + "Rudra_chamaka_krama_paatam.pdf",
        },
        {
            id: "C027",
            label: "Purusha_suktham",
            description: "Purusha_suktham",
            keywords: "Purusha_suktham",
            file: categoryFolders.C + "Purusha_suktham.pdf",
        },
        {
            id: "C028",
            label: "Shri_suktham_rigvedam",
            description: "Shri_suktham_rigvedam",
            keywords: "Shri_suktham_rigvedam",
            file: categoryFolders.C + "Shri_suktham_rigvedam.pdf",
        },
        {
            id: "C025",
            label: "Durga_suktham",
            description: "Durga_suktham",
            keywords: "Durga_suktham",
            file: categoryFolders.C + "Durga_suktham.pdf",
        },
        {
            id: "C024",
            label: "Narayana_suktham",
            description: "Narayana_suktham",
            keywords: "Narayana_suktham",
            file: categoryFolders.C + "Narayana_suktham.pdf",
        },
        {
            id: "C022",
            label: "Arunaprashnam",
            description: "Arunaprashnam",
            keywords: "Arunaprashnam",
            file: categoryFolders.C + "Arunaprashnam.pdf",
        },
        {
            id: "C029",
            label: "Medha_suktham",
            description: "Medha_suktham",
            keywords: "Medha_suktham",
            file: categoryFolders.C + "Medha_suktham.pdf",
        },
        {
            id: "C030",
            label: "Neela_suktham",
            description: "Neela_suktham",
            keywords: "Neela_suktham",
            file: categoryFolders.C + "Neela_suktham.pdf",
        },
        {
            id: "C031",
            label: "Vishnu_suktham",
            description: "Vishnu_suktham",
            keywords: "Vishnu_suktham",
            file: categoryFolders.C + "Vishnu_suktham.pdf",
        },
        {
            id: "C032",
            label: "Bhaagya_suktham",
            description: "Bhaagya_suktham",
            keywords: "Bhaagya_suktham",
            file: categoryFolders.C + "Bhaagya_suktham.pdf",
        },
        {
            id: "C034",
            label: "Surya_namaskaaram_poorvaangam",
            description: "Surya_namaskaaram_poorvaangam",
            keywords: "Surya_namaskaaram_poorvaangam",
            file: categoryFolders.C + "Surya_namaskaaram_poorvaangam.pdf",
        },
        {
            id: "C036",
            label: "Udaka_shanthi",
            description: "Udaka_shanthi",
            keywords: "Udaka_shanthi",
            file: categoryFolders.C + "Udaka_shanthi.pdf",
        },
        {
            id: "C037",
            label: "Shiva_sthuthi",
            description: "Shiva_sthuthi",
            keywords: "Shiva_sthuthi",
            file: categoryFolders.C + "Shiva_sthuthi.pdf",
        },
        {
            id: "C039",
            label: "Bhu_suktham",
            description: "Bhu_suktham",
            keywords: "Bhu_suktham",
            file: categoryFolders.C + "Bhu_suktham.pdf",
        },
        {
            id: "C040",
            label: "Shri_hanumath_suktham",
            description: "Shri_hanumath_suktham",
            keywords: "Shri_hanumath_suktham",
            file: categoryFolders.C + "Shri_hanumath_suktham.pdf",
        },
    ],
    D:
    [
        {
            id: "D001",
            label: "Ganapathi_suktham_rigvedam",
            description: "Ganapathi_suktham_rigvedam",
            keywords: "Ganapathi_suktham_rigvedam",
            file: categoryFolders.D + "Ganapathi_suktham_rigvedam.pdf",
        },
        {
            id: "D006",
            label: "Pavamaana_suktham",
            description: "Pavamaana_suktham",
            keywords: "Pavamaana_suktham",
            file: categoryFolders.D + "Pavamaana_suktham.pdf",
        },
        {
            id: "D018",
            label: "Kumaara_suktham",
            description: "Kumaara_suktham",
            keywords: "Kumaara_suktham",
            file: categoryFolders.D + "Kumaara_suktham.pdf",
        },
        {
            id: "D015",
            label: "Shri_rudram_chamakam",
            description: "Shri_rudram_chamakam",
            keywords: "Shri_rudram_chamakam",
            file: categoryFolders.D + "Shri_rudram_chamakam.pdf",
        },
        {
            id: "D013",
            label: "Rudra_chamaka_krama_paatam",
            description: "Rudra_chamaka_krama_paatam",
            keywords: "Rudra_chamaka_krama_paatam",
            file: categoryFolders.D + "Rudra_chamaka_krama_paatam.pdf",
        },
        {
            id: "D007",
            label: "Purusha_suktham",
            description: "Purusha_suktham",
            keywords: "Purusha_suktham",
            file: categoryFolders.D + "Purusha_suktham.pdf",
        },
        {
            id: "D008",
            label: "Shri_suktham_rigvedam",
            description: "Shri_suktham_rigvedam",
            keywords: "Shri_suktham_rigvedam",
            file: categoryFolders.D + "Shri_suktham_rigvedam.pdf",
        },
        {
            id: "D005",
            label: "Durga_suktham",
            description: "Durga_suktham",
            keywords: "Durga_suktham",
            file: categoryFolders.D + "Durga_suktham.pdf",
        },
        {
            id: "D004",
            label: "Narayana_suktham",
            description: "Narayana_suktham",
            keywords: "Narayana_suktham",
            file: categoryFolders.D + "Narayana_suktham.pdf",
        },
        {
            id: "D003",
            label: "Nakshatra_suktham",
            description: "Nakshatra_suktham",
            keywords: "Nakshatra_suktham",
            file: categoryFolders.D + "Nakshatra_suktham.pdf",
        },
        {
            id: "D002",
            label: "Arunaprashnam",
            description: "Arunaprashnam",
            keywords: "Arunaprashnam",
            file: categoryFolders.D + "Arunaprashnam.pdf",
        },
        {
            id: "D009",
            label: "Medha_suktham",
            description: "Medha_suktham",
            keywords: "Medha_suktham",
            file: categoryFolders.D + "Medha_suktham.pdf",
        },
        {
            id: "D010",
            label: "Neela_suktham",
            description: "Neela_suktham",
            keywords: "Neela_suktham",
            file: categoryFolders.D + "Neela_suktham.pdf",
        },
        {
            id: "D011",
            label: "Vishnu_suktham",
            description: "Vishnu_suktham",
            keywords: "Vishnu_suktham",
            file: categoryFolders.D + "Vishnu_suktham.pdf",
        },
        {
            id: "D012",
            label: "Bhaagya_suktham",
            description: "Bhaagya_suktham",
            keywords: "Bhaagya_suktham",
            file: categoryFolders.D + "Bhaagya_suktham.pdf",
        },
        {
            id: "D014",
            label: "Surya_namaskaaram_poorvaangam",
            description: "Surya_namaskaaram_poorvaangam",
            keywords: "Surya_namaskaaram_poorvaangam",
            file: categoryFolders.D + "Surya_namaskaaram_poorvaangam.pdf",
        },
        {
            id: "D016",
            label: "Udaka_shanthi",
            description: "Udaka_shanthi",
            keywords: "Udaka_shanthi",
            file: categoryFolders.D + "Udaka_shanthi.pdf",
        },
        {
            id: "D017",
            label: "Shiva_sthuthi",
            description: "Shiva_sthuthi",
            keywords: "Shiva_sthuthi",
            file: categoryFolders.D + "Shiva_sthuthi.pdf",
        },
        {
            id: "D019",
            label: "Bhu_suktham",
            description: "Bhu_suktham",
            keywords: "Bhu_suktham",
            file: categoryFolders.D + "Bhu_suktham.pdf",
        },
        {
            id: "D023",
            label: "Nakshatra_suktham",
            description: "Nakshatra_suktham",
            keywords: "Nakshatra_suktham",
            file: categoryFolders.D + "Nakshatra_suktham.pdf",
        },
        {
            id: "D020",
            label: "Shri_hanumath_suktham",
            description: "Shri_hanumath_suktham",
            keywords: "Shri_hanumath_suktham",
            file: categoryFolders.D + "Shri_hanumath_suktham.pdf",
        },
        {
            id: "D038",
            label: "Kumaara_suktham",
            description: "Kumaara_suktham",
            keywords: "Kumaara_suktham",
            file: categoryFolders.D + "Kumaara_suktham.pdf",
        },
        {
            id: "D026",
            label: "Pavamaana_suktham",
            description: "Pavamaana_suktham",
            keywords: "Pavamaana_suktham",
            file: categoryFolders.D + "Pavamaana_suktham.pdf",
        },
        {
            id: "D021",
            label: "Ganapathi_suktham_rigvedam",
            description: "Ganapathi_suktham_rigvedam",
            keywords: "Ganapathi_suktham_rigvedam",
            file: categoryFolders.D + "Ganapathi_suktham_rigvedam.pdf",
        },
        {
            id: "D035",
            label: "Shri_rudram_chamakam",
            description: "Shri_rudram_chamakam",
            keywords: "Shri_rudram_chamakam",
            file: categoryFolders.D + "Shri_rudram_chamakam.pdf",
        },
        {
            id: "D033",
            label: "Rudra_chamaka_krama_paatam",
            description: "Rudra_chamaka_krama_paatam",
            keywords: "Rudra_chamaka_krama_paatam",
            file: categoryFolders.D + "Rudra_chamaka_krama_paatam.pdf",
        },
        {
            id: "D027",
            label: "Purusha_suktham",
            description: "Purusha_suktham",
            keywords: "Purusha_suktham",
            file: categoryFolders.D + "Purusha_suktham.pdf",
        },
        {
            id: "D028",
            label: "Shri_suktham_rigvedam",
            description: "Shri_suktham_rigvedam",
            keywords: "Shri_suktham_rigvedam",
            file: categoryFolders.D + "Shri_suktham_rigvedam.pdf",
        },
        {
            id: "D025",
            label: "Durga_suktham",
            description: "Durga_suktham",
            keywords: "Durga_suktham",
            file: categoryFolders.D + "Durga_suktham.pdf",
        },
        {
            id: "D024",
            label: "Narayana_suktham",
            description: "Narayana_suktham",
            keywords: "Narayana_suktham",
            file: categoryFolders.D + "Narayana_suktham.pdf",
        },
        {
            id: "D022",
            label: "Arunaprashnam",
            description: "Arunaprashnam",
            keywords: "Arunaprashnam",
            file: categoryFolders.D + "Arunaprashnam.pdf",
        },
        {
            id: "D029",
            label: "Medha_suktham",
            description: "Medha_suktham",
            keywords: "Medha_suktham",
            file: categoryFolders.D + "Medha_suktham.pdf",
        },
        {
            id: "D030",
            label: "Neela_suktham",
            description: "Neela_suktham",
            keywords: "Neela_suktham",
            file: categoryFolders.D + "Neela_suktham.pdf",
        },
        {
            id: "D031",
            label: "Vishnu_suktham",
            description: "Vishnu_suktham",
            keywords: "Vishnu_suktham",
            file: categoryFolders.D + "Vishnu_suktham.pdf",
        },
        {
            id: "D032",
            label: "Bhaagya_suktham",
            description: "Bhaagya_suktham",
            keywords: "Bhaagya_suktham",
            file: categoryFolders.D + "Bhaagya_suktham.pdf",
        },
        {
            id: "D034",
            label: "Surya_namaskaaram_poorvaangam",
            description: "Surya_namaskaaram_poorvaangam",
            keywords: "Surya_namaskaaram_poorvaangam",
            file: categoryFolders.D + "Surya_namaskaaram_poorvaangam.pdf",
        },
        {
            id: "D036",
            label: "Udaka_shanthi",
            description: "Udaka_shanthi",
            keywords: "Udaka_shanthi",
            file: categoryFolders.D + "Udaka_shanthi.pdf",
        },
        {
            id: "D037",
            label: "Shiva_sthuthi",
            description: "Shiva_sthuthi",
            keywords: "Shiva_sthuthi",
            file: categoryFolders.D + "Shiva_sthuthi.pdf",
        },
        {
            id: "D039",
            label: "Bhu_suktham",
            description: "Bhu_suktham",
            keywords: "Bhu_suktham",
            file: categoryFolders.D + "Bhu_suktham.pdf",
        },
        {
            id: "D040",
            label: "Shri_hanumath_suktham",
            description: "Shri_hanumath_suktham",
            keywords: "Shri_hanumath_suktham",
            file: categoryFolders.D + "Shri_hanumath_suktham.pdf",
        },
    ],
    E:
    [
    ],
    F:
    [
    ],
    G:
    [
        {
            id: "G001",
            label: "Shri_hanumath_suktham",
            description: "Shri_hanumath_suktham",
            keywords: "Shri_hanumath_suktham",
            file: categoryFolders.G + "Shri_hanumath_suktham.pdf",
        },
    ],
    H:
    [
    ],
    I:
    [
    ],
    J:
    [
    ],
    K:
    [
    ],
    L:
    [
    ],
    M:
    [
    ],
    N:
    [
    ],
    O:
    [
    ],
    P:
    [
    ],
    Q:
    [
    ],
    R:
    [
    ],
    S:
    [
    ],
    T:
    [
    ],
};